data_config:
  dataset_name: legal

federated_config:
  rounds: 20
  sample: 1.0
  rank: -2
  partition_method: silo
  clients_num: 10
  pson: true # local eval and test
  pson_round_len: 1  # local client eval per 1 round，
  pson_log_test_len: 5  # local client test per 5 round

model_config:
  # model_type: bert
  model_type: roberta-wwm-ext
  model_output_mode: token_classification_crf
  permutation_layers: false
  client_model_layers: [0,1,2]
  server_model_layers: [0,1,2]
  tuning_type:
#  tuning_type: adapter_roberta-base
#  tuning_type: soft_prompt_roberta-base
#  tuning_type: lora_roberta-base
#  tuning_type: bitfit_roberta-base
#  tuning_type: prefix_roberta-base

training_config:
  per_device_train_batch_size: 32
  num_train_epochs: 20
  learning_rate: 5e-5
  metric_name: legal
  seed: 42
  do_predict: true
