data_config:
  dataset_name: legal

federated_config:
  rank: -1
  rounds: 20
  sample: 1.0
  partition_method: silo
  clients_num: 24
  alpha: 1.0
  pson: true # local eval and test
  pson_round_len: 1  # local client eval per 1 round，
  pson_log_test_len: 5  # local client test per 5 round

model_config:
  model_type: roberta-wwm-ext
  # model_type: gpt2-chinese-cluecorpussmall
  # model_output_mode: seq_generation
  # model_output_mode: seq_classification
  model_output_mode: seq_regression
#  model_output_mode: token_classification
  permutation_layers: true
  client_model_layers: [0,1,2,3,4,5]
  server_model_layers: [0,1,2,3,4,5]
  tuning_type:
#  tuning_type: adapter_roberta-base
#  tuning_type: soft_prompt_roberta-base
#  tuning_type: lora_roberta-base
#  tuning_type: bitfit_robert-base
#  tuning_type: prefix_robert-base

training_config:
  per_device_train_batch_size: 16
  num_train_epochs: 20
  learning_rate: 5e-5
  metric_name: legal
  seed: 42
  do_predict: true