data_config:
  dataset_name: legal

federated_config:
  rounds: 20
  sample: 1.0
  clients_num: 10
  alpha: 0.1
  pson: false # local test
  pson_round_len: 1  # local client eval per 10 round，
  test_rounds: false  # global server test
  log_test_len: 1  # global server test freq. And default 10 global test freq
  eval_rounds: true  # global server eval
  log_eval_len: 1  # global server eval freq. And default 1 global eval freq
  prox_mu: 0.005

model_config:
  model_type: roberta-wwm-ext
  model_output_mode: seq_classification
  permutation_layers: false
  client_model_layers: [0,1,2]
  server_model_layers: [0,1,2]
  tuning_type:
#  tuning_type: adapter_roberta-base
#  tuning_type: soft_prompt_roberta-base
#  tuning_type: lora_roberta-base
#  tuning_type: bitfit_roberta-base
#  tuning_type: prefix_roberta-base

training_config:
  per_device_train_batch_size: 16
  num_train_epochs: 1
  learning_rate: 5e-5
  metric_name: legal
  seed: 42
  do_predict: true
  model_save: false # save model to analysis
  metric_for_best_model: f1_macro
  greater_is_better: true
